---
- hosts: worker
  tasks:
  - name: Installation des pakages {{ item }}
    yum:
      name: "{{ item }}"
      state: present
    when: ansible_distribution == "CentOS"
    loop:
      - httpd
      - epel-release
      - vim
      - htop        
  - name: Demmarrage et activation du service apache (httpd)
    systemd:
      name: httpd
      state: started
      enabled: yes
