---
- hosts: worker
  vars_files:
    user_vars.yml 
  tasks:        
  - name: Ajout des groups {{ groupe }}
    group:
      name: "{{ item }}"
    loop:
      "{{ groupe }}"
  - name: Creation d'utilisateurs {{ user }}
    user:
      name: "{{ item }}"
    loop:
      "{{ user }}"
