# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"

  # Docker Master Server
  config.vm.define "dockermaster" do |dockermaster|
    dockermaster.vm.box = "centos/7"
    dockermaster.vm.hostname = "dockermaster.plb.form"
    dockermaster.vm.network "private_network", ip: "172.42.42.100"
    dockermaster.vm.provider "virtualbox" do |v|
      v.name = "dockermaster"
      v.memory = 2048
      v.cpus = 2
    end
    dockermaster.vm.provision "shell", path: "bootstrap.sh"
  end

  NodeCount = 2

  # Docker Worker Nodes
  (1..NodeCount).each do |i|
    config.vm.define "dockerworker#{i}" do |workernode|
      workernode.vm.box = "centos/7"
      workernode.vm.hostname = "dockerworker#{i}.plb.form"
      workernode.vm.network "private_network", ip: "172.42.42.10#{i}"
      workernode.vm.provider "virtualbox" do |v|
        v.name = "dockerworker#{i}"
        v.memory = 1024
        v.cpus = 1
      end
      workernode.vm.provision "shell", path: "bootstrap.sh"
    end
  end

end
